export type Airport = {
  id: number
  city_id: string
  dest_id: string
  dest_type: string
  language_code: string
  city_name: string
  city_name_en: string
  local_name: null
  speak_name: null
  country: string
  is_schengen: string
  is_multiairport: string
  state_code: null
  state_name: null
  display_name: string
  has_city: string
  IATA: string
  ICAO: string
  fs_id: string
  timezone: string
  elevation: string
  name: string
  prio: string
  prio2: string
  prio3: string
  ui_display_name: string
  ui_display_name_in_text_field: string
  slug: string
  url_slug: null
  viator_url: string
  viator_id: string
  viator_urlname: string
  latitude: string
  longitude: string
  country_code: string
  continent: string
  no_routes: string
  no_routes_airlines: string
  wiki_url: null
  classification: string
  text_generated: string
  text_generated_short: string
  airport_image_credits: string
  created_at: string
  updated_at: string
  fr24_scanned_at: string
  has_image: string
  on_water: null
  has_travelcar: string
  country_id: string
  price_requested: string
  delayed15: string
  delayed30: string
  delayed45: string
  onTime: string
  normalizedScore: string
  canceled: string
  delayindex_datestart: string
  delayindex_dateend: string
  delayindex_flights: string
  delayindex_observations: string
  delta: string
}
export type DB_Airport = Airport
